print("Enter Eight Numbers")
num_set = set()
a=int(input("1st No: "))
num_set.add(a)
b=int(input("2nd No: "))
num_set.add(b)
c=int(input("3rd No: "))
num_set.add(c)
d=int(input("4th No: "))
num_set.add(d)
e=int(input("5th No: "))
num_set.add(e)
f=int(input("6th No: "))
num_set.add(f)
g=int(input("7th No: "))
num_set.add(g)
h=int(input("8th No: "))
num_set.add(h)

print("Display the unique numbers")
print(num_set)

